---
title: "Lab 06 - Functions and iterations"
author: "Blair Rafferty"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table,
    quality = color
  )
```


## Exercise 1

```{r}
Diamonds <- diamonds %>% mutate(quality = as.numeric(as.factor(quality)),
                                clarity = as.numeric(as.factor(clarity)))

# High clarity and low quality is best

Diamonds %>%
  summarise(
    mean_price = mean(price),
    median_price = median(price)
  )
count(Diamonds, price >= mean(price))
```


## Exercise 2

```{r}

Diamonds <- Diamonds %>% 
  mutate(table_mm = table_pct * width_mm / 100, round(table_mm, digits=2)) %>%
  select(-table_mm)

Diamonds <- Diamonds %>% rename(
  table_mm = `round(table_mm, digits = 2)`
)

View(Diamonds)

summarise(Diamonds, mean_table = mean(length_mm))

# table_mm arithmetic mean within each clarity category

mean_table_mm = numeric(8)

for (i in 1:8){
  mean_table_mm[i] <- as.numeric(Diamonds %>% filter(clarity == i) %>% summarise(mean(table_mm)))
}

Diamonds %>% group_by(clarity) %>% summarise(mean(table_mm))
```

As clarity increases, table length decreases

## Exercise 3




## Exercise 4

```{r}
# Write gmean() command



```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
